global:
    scrape_interval:     15s
    evaluation_interval: 5m

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       # - alertmanager:9093
#
# # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# rule_files:
#   # - "first_rules.yml"
#   # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'cassandra'
      dns_sd_configs:
          - names: ['cassandra-1.locol.dev', 'cassandra-2.locol.dev', 'cassandra-3.locol.dev']
            type: 'A'
            port: 6666
