version: "3"

services:
    cassandra_node1:
        image: cassandra:3.11
        restart: always
        # ports:
        #     - 9042:9042   # cassandra port
        #     - 6666:6666   # jmx_exporter
        volumes:
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/jmx_exporter/:/usr/share/cassandra/jmx_exporter:ro
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/cassandra-env.sh:/etc/cassandra/cassandra-env.sh:ro

    cassandra_node3:
        image: cassandra:3.11
        restart: always
        environment:
            CASSANDRA_SEEDS: cassandra_node1
        volumes:
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/jmx_exporter/:/usr/share/cassandra/jmx_exporter:ro
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/cassandra-env.sh:/etc/cassandra/cassandra-env.sh:ro

    cassandra_node2:
        image: cassandra:3.11
        restart: always
        environment:
            CASSANDRA_SEEDS: cassandra_node1
        volumes:
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/jmx_exporter/:/usr/share/cassandra/jmx_exporter:ro
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/cassandra-env.sh:/etc/cassandra/cassandra-env.sh:ro
