version: "3"

services:
    cassandra-1.locol.dev:
        labels:
            chaos: "true"
        image: cassandra:3.11
        restart: always
        # ports:
        #     - 9042:9042   # cassandra port
        #     - 6666:6666   # jmx_exporter
        volumes:
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/jmx_exporter/:/usr/share/cassandra/jmx_exporter:ro
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/cassandra-env.sh:/etc/cassandra/cassandra-env.sh:ro

    cassandra-2.locol.dev:
        labels:
            chaos: "true"
        image: cassandra:3.11
        restart: always
        environment:
            CASSANDRA_SEEDS: cassandra-1.locol.dev
        volumes:
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/jmx_exporter/:/usr/share/cassandra/jmx_exporter:ro
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/cassandra-env.sh:/etc/cassandra/cassandra-env.sh:ro

    cassandra-3.locol.dev:
        labels:
            chaos: "true"
        image: cassandra:3.11
        restart: always
        environment:
            CASSANDRA_SEEDS: cassandra-1.locol.dev
        volumes:
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/jmx_exporter/:/usr/share/cassandra/jmx_exporter:ro
            - ${CURDIR:?CURDIR not set}/docker-compose/cassandra/cassandra-env.sh:/etc/cassandra/cassandra-env.sh:ro
