version: "3"

services:
    chaos.locol.dev:
        image: docker:18.09
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${CURDIR}/docker-compose/chaos/chaos.sh:/var/run/chaos.sh:ro
        entrypoint: /var/run/chaos.sh
