version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.7.2
    ports:
    - 9091:9090
    volumes:
    - ${CURDIR:?env var CURDIR not set/empty}/docker-compose/prometheus/config.yml:/etc/prometheus/prometheus.yml
