version: "3"

services:
    prometheus.locol.dev:
        image: prom/prometheus:v2.7.2
        restart: always
        # ports:
        #     - 9091:9090
        volumes:
            - ${CURDIR}/docker-compose/prometheus/config.yml:/etc/prometheus/prometheus.yml
